name: steamrec
channels:
  - conda-forge
dependencies:
  - python=3.11.3
  - flask=2.2.3
  - flask_cors=3.0.10
  - requests=2.28.2
  - scikit-surprise=1.1.3
  - pandas=1.5.3
  - nodejs=18.15.0
  - pip
  - pip:
    - howlongtobeatpy==1.0.5

